name: Deploy Django Backend to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Deploy to Oracle Cloud Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -e
          
          echo "=== Starting Deployment ==="
          
          # 프로젝트 디렉토리 확인 및 클론
          if [ ! -d ~/prj-sketch-backend ]; then
            echo "Repository not found. Cloning..."
            git clone https://github.com/deerking0923/prj-sketch-backend.git ~/prj-sketch-backend
          else
            echo "Repository exists. Pulling latest changes..."
            cd ~/prj-sketch-backend
            git reset --hard HEAD
            git pull origin main
          fi
          
          cd ~/prj-sketch-backend
          
          # 가상환경 활성화
          echo "=== Activating Virtual Environment ==="
          source venv/bin/activate
          
          # 의존성 업데이트
          echo "=== Installing Dependencies ==="
          pip install -r requirements.txt
          
          # .env 파일 생성
          echo "=== Creating .env File ==="
          cat > .env << 'ENVEOF'
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG=${{ secrets.DEBUG }}
          SERVER_IP=${{ secrets.SERVER_IP }}
          ALLOWED_HOSTS=localhost,127.0.0.1,${{ secrets.SERVER_IP }}
          LANGUAGE_CODE=en-us
          TIME_ZONE=Asia/Seoul
          FRONTEND_PORT=3000
          BACKEND_PORT=8080
          ENVEOF
          
          # 마이그레이션 실행
          echo "=== Running Migrations ==="
          python manage.py migrate
          
          # 정적 파일 수집
          echo "=== Collecting Static Files ==="
          python manage.py collectstatic --noinput
          
          # 기존 Django 서버 종료
          echo "=== Stopping Existing Django Server ==="
          screen -S django -X quit || echo "No existing server"
          
          sleep 3
          
          # 새로운 Django 서버 시작
          echo "=== Starting New Django Server ==="
          screen -dmS django bash -c 'cd ~/prj-sketch-backend && source venv/bin/activate && python manage.py runserver 0.0.0.0:8000 > django.log 2>&1'
          
          sleep 5
          
          # 서버 실행 확인
          if screen -list | grep -q "django"; then
            echo "✅ Django server is running"
          else
            echo "❌ Failed to start Django server"
            exit 1
          fi
          
          # 최근 로그
          echo "=== Recent Logs ==="
          tail -n 20 django.log 2>/dev/null || echo "No logs yet"
          
          echo "=== Deployment Completed at $(date) ==="