name: Deploy Django Backend to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Debug Secrets
      run: |
        echo "Checking if secrets are loaded..."
        if [ -z "${{ secrets.SERVER_HOST }}" ]; then
          echo "ERROR: SERVER_HOST is empty or not set"
        else
          echo "SERVER_HOST is set (length: ${#SERVER_HOST})"
        fi
        if [ -z "${{ secrets.SERVER_USERNAME }}" ]; then
          echo "ERROR: SERVER_USERNAME is empty or not set"
        else
          echo "SERVER_USERNAME is set"
        fi
        if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "ERROR: SSH_PRIVATE_KEY is empty or not set"
        else
          echo "SSH_PRIVATE_KEY is set (first 50 chars): ${{ secrets.SSH_PRIVATE_KEY }} | cut -c1-50"
        fi
    
    - name: Deploy to Oracle Cloud Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Connected successfully!"